spring:
    application:
        name: cloud-eureka-server #服务注册中心应用名 对应 application

server:
    port: 8761 #启动端口 8761 为eureka server默认端口 若使用其它端口需要声明defaultZoneUrl

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server