spring:
  application:
      name: cloud-gateway #网关名
server:
  port: 9000 #网关端口

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        home-page-url-path: /
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


  redis:
      database: 2
      host: 127.0.0.1
      jedis:
        pool:
            max-active: 20
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
#  springcloud gateway 配置
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # ================网关路由规则=====================
      - id: cloud-gateway
        uri: lb://liu #路由后执行的uri
        order: 8000 #改组路由规则顺序
        predicates:
        - Path=/api/**  #访问uri 规则 符合该规则都由该组路由规则匹配
        filters:
        - StripPrefix=0 #过滤前面n=0个路径前缀
        - name: Hystrix
          args:
            name: authHystrixCommand
            fallbackUri: forward:/hystrixTimeout
gate:
  ignore:
    startWith: /jwt  #忽略以/jwt为前缀的uri访问请求 即该访问不加入路由


logging:
  level:
    com.scscloud.gateway: debug #日志级别
